### ISSUE TITLE
NgModel

### ISSUE THREAD

**Issue by AHMADADEROZAK** [tanishqmanuja/ng-md3-ionic-playground#1]
Cannot use ngModel binding with eror : Error: NG01203: No value accessor for form control unspecified name

` <div>data : {{inputField}}</div>
      <div style="padding: 16px;">
      <md-outlined-text-field 
      label="Text Outlined"
      [(ngModel)]="inputField"
      placeholder="Masukan Sample Text">
    </md-outlined-text-field>`

**Comment by tanishqmanuja** [comment]
md-outline-text-field is not an angular element or native html element. Hence as the error says Value Accessor Interface is not implemented. To implement it I suggest you look into Control Value Accessor topic, josh morony on YT have some great vids.
